[zotero]
library_id = "12345"              # change this
library_type = "user"             # you probably want to keep this
zotero_api_key = "<your api key>" # Get one from Zotero with Read/Write access
zotero_directory = "~/Zotero"     # change to system path, depending on your OS

[system]
# default MacOS Chrome path. Adjust as needed
path_to_chrome_exe = "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome"
save_dir = "/tmp/zotero-converter"
